# Discord Logs Configuration

# Discord webhook URL
webhook-url: "YOUR_WEBHOOK_URL"

# Plugin language (english, french, spanish)
language: "english"

# Logging settings
logging:
  chest-interactions: true

# MySQL Configuration
mysql:
  enabled: false
  host: "localhost"
  port: 3306
  database: "minecraft_logs"
  username: "root"
  password: "password"
  table: "discord_logs"

  # Debug settings
  debug: false